version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017/?tls=false&authMechanism=DEFAULT
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
